### ISSUE TITLE
appの操作画像を掲載

### ISSUE THREAD

**Issue by ruiishiguro** [ruiishiguro/smack#10]
How to playの下に操作画面を掲載。
Charactorは削除

**Comment by ruiishiguro** [comment]
@mitsumashoko 
Charactor紹介を削除して、代わりに操作画面3枚を掲載するように変更してください。

**Comment by mitsumashoko** [comment]
#11 と同時に対応しました

**Comment by ruiishiguro** [comment]
@Sayuri-Y 
キャラクターを削除してappの操作画面を掲載することになりました。
モバイル版は横スクロールになりますので実装の変更よろしくお願いします！

**Comment by Sayuri-Y** [comment]
@ruiishiguro 

対応完了しました！
管理画面上は、Character を App に変更しております！
- https://smack.gmprojects.dev/
smack / marunouchi
- https://smack.gmprojects.dev/wp-admin/

**Comment by ruiishiguro** [comment]
@Sayuri-Y 
ありがとうございます！
確認致しました。
