### ISSUE TITLE
smack appアイコンを掲載

### ISSUE THREAD

**Issue by ruiishiguro** [ruiishiguro/smack#11]
『さぁ、SMACKと街へ出よう』テキストに下にsmack appアイコンを掲載。
実装時はリンク出し分け
https://www.figma.com/proto/4g6rmBH1DPWT9NBVV7OCfg/%E3%83%AF%E3%82%A4%E3%83%A4%E3%83%BC%E3%83%95%E3%83%AC%E3%83%BC%E3%83%A0?page-id=0%3A1&node-id=1950%3A132&viewport=1771%2C-592%2C0.44&scaling=scale-down&starting-point-node-id=1795%3A36

**Comment by ruiishiguro** [comment]
@mitsumashoko 
『さぁ、SMACKと街へ出よう』テキストに下にsmack appアイコンを追加してください。

**Comment by mitsumashoko** [comment]
@ruiishiguro 
こちら対応しました！ご確認よろしくおねがいします！

- PC 
https://www.figma.com/proto/4g6rmBH1DPWT9NBVV7OCfg/%E3%83%AF%E3%82%A4%E3%83%A4%E3%83%BC%E3%83%95%E3%83%AC%E3%83%BC%E3%83%A0?page-id=1828%3A257&node-id=1828%3A258&viewport=441%2C196%2C0.13&scaling=min-zoom

- SP
https://www.figma.com/proto/4g6rmBH1DPWT9NBVV7OCfg/%E3%83%AF%E3%82%A4%E3%83%A4%E3%83%BC%E3%83%95%E3%83%AC%E3%83%BC%E3%83%A0?page-id=1755%3A26&node-id=1757%3A27&viewport=552%2C265%2C0.25&scaling=scale-down

**Comment by ruiishiguro** [comment]
@mitsumashoko 
ありがとうございます！
ばっちりかと思います！

**Comment by ruiishiguro** [comment]
@Sayuri-Y 
実装よろしくお願いします！

**Comment by Sayuri-Y** [comment]
@ruiishiguro 

追加しました！
- https://smack.gmprojects.dev/
smack / marunouchi
- https://smack.gmprojects.dev/wp-admin/

**Comment by ruiishiguro** [comment]
@Sayuri-Y 
バッチリかと！
