### ISSUE TITLE
サイト移植

### ISSUE THREAD

**Issue by ruiishiguro** [ruiishiguro/smack#12]
theme,プラグイン、プラグイン設定、現在アップされているデータ一式を以下に移植
[https://marunouchi.placy.city/](https://marunouchi.placy.city/?fbclid=IwAR0C6gIfFqPN8uJLeXemmzjbDjSBG8ogHdBgpPrcALIFk8LNhCE6JmrG3ZE)
[https://marunouchi.placy.city/wp-admin/](https://marunouchi.placy.city/wp-admin/?fbclid=IwAR0amVU9lry2dJft8zjSCenRcEAY7JncxKHbV44FPq5XkKebDcQVgnza64o)

`marunouchi`というフォルダ内にWordPressを設定。
データベースも独立させています。

**Comment by ruiishiguro** [comment]
@Sayuri-Y 
一応issueも作っておきました

**Comment by Sayuri-Y** [comment]
@ruiishiguro 

これでどうだ！
https://marunouchi.placy.city/

お問い合わせはコメントアウトしてます。
利用規約・プライバシーポリシーは既存から引っ張ってきたもので大丈夫でしょうか？

**Comment by ruiishiguro** [comment]
@Sayuri-Y 
ありがとうございます！
バッチリかと！
こちら更新踏まえて引き取ります！

**Comment by Sayuri-Y** [comment]
@ruiishiguro 

よろしくお願いいたします！
ちなみにちょっと分かりにくくて申し訳ないのですが、、、

ここのモーダルの部分ですが、

![スクリーンショット 0004-07-14 23 44 56](https://user-images.githubusercontent.com/81949280/179010246-04a63d42-93da-4138-afd8-f70929205b5e.png)


```html
<div class="group3__artist-wrap"><!-- start artist 0101 -->
  <a class="group3__artist md-btn" href="" data-target="0101" >
	  <figure><img class="lazyload" data-src="/assets/images/artist_1_01.png" /></figure>
	  <p class="text-en">millennium parade</p>
  </a>
  <div class="modal" id="0101" ><!-- start modal 0101 -->
	  省略
  </div><!-- end modal 0101 -->				
</div><!-- end artist 0101 -->
```

半角英数ならなんでも大丈夫なんですが、アーティスト`data-target="0101"` とモーダルの詳細 ` id="0101"` を同じ英数字に設定するとモーダルが動くようになってます！
（この場合だと `0101 `）

```html
  <a class="group3__artist md-btn" href="" data-target="0101" >
```
```html
  <div class="modal" id="0101" >
```

**Comment by ruiishiguro** [comment]
@Sayuri-Y 
もろもろありがとうございます！
データ変更も無事に出来たのでクローズします！
