### ISSUE TITLE
デザイン確定

### ISSUE THREAD

**Issue by ruiishiguro** [ruiishiguro/smack#2]
ワイヤー
https://www.figma.com/file/4g6rmBH1DPWT9NBVV7OCfg/%E3%83%AF%E3%82%A4%E3%83%A4%E3%83%BC%E3%83%95%E3%83%AC%E3%83%BC%E3%83%A0?node-id=0%3A1

**Comment by ruiishiguro** [comment]
- [x] モバイルにモーダルにスペシャルアイテムを追加
- [x] モバイルにモーダルにSNSリンクを追加
- [x] デスクトップ版のモーダルにスペシャルアイテムのアイテム名とテキストを追加
- [x] モーダルの背景に透過面を敷く
- [x] Placyのロゴマークを以下に差し替え
![placy-logo](https://user-images.githubusercontent.com/1421966/177239496-f19d4503-0e5d-4701-be92-ef5216f967ec.png)

**Comment by mitsumashoko** [comment]
@ruiishiguro 
確認ありがとうございます！
こちらわかりにくくてすみません、モーダル内の設定をしているので、SP版はこちらより確認していただけますでしょうか。
https://www.figma.com/proto/4g6rmBH1DPWT9NBVV7OCfg/%E3%83%AF%E3%82%A4%E3%83%A4%E3%83%BC%E3%83%95%E3%83%AC%E3%83%BC%E3%83%A0?page-id=1755%3A26&node-id=1855%3A405&viewport=468%2C319%2C0.5&scaling=scale-down

再度ご確認よろしくおねがいします！

**Comment by ruiishiguro** [comment]
@mitsumashoko 
あー、ごめん。理解しました。

バッチリかと思いますが一点だけ。
デスクトップ版の荘子itのプロフィール写真が仮データなのでモバイルと同じにしてください。

**Comment by mitsumashoko** [comment]
@ruiishiguro 
失礼しました！変更しました！

**Comment by ruiishiguro** [comment]
@mitsumashoko 
サンキュー、確認しました。
こちらでクライアントに展開します。フィードバックがあればまた相談します。

**Comment by ruiishiguro** [comment]
一旦確定したのでクローズします。
フィードバックがあった場合は別issueで進行します。
