### ISSUE TITLE
ページ実装

### ISSUE THREAD

**Issue by ruiishiguro** [ruiishiguro/smack#4]
### 動画
仕様は実装と要確認、以下が希望内容です。
youtube動画を背景で自動再生（音声無し）、クリックで動画をモーダルで表示して音声付き再生させる
その際、モーダル表示時は背景の動画を停止、モーダルをクローズしたタイミングで再生。ただし、1時間調べてこの仕様が難しい場合は背景を透過にしないで再生させたままにする。

### Music@? in Marunouchi Quest
以下を管理画面から差し替え出来るように実装
- [x] リードテキスト
- [x] メイン画像

### How to play
- [x] 画像とテキストをセットにして管理画面から変更できるように設定

### Character
- [x] 画像とキャラクター名をセットにして管理画面から変更できるように設定

### Artist
以下を管理画面から差し替え出来るように実装
- [x] リードテキスト
- [x] アーティスト情報（画像、アーティスト名、プロフィール、オフィシャルサイト、SNSリンク。スペシャルアイテム情報）

### さぁ、SMACKと街へ出よう。
以下を管理画面から差し替え出来るように実装
- [x] テキスト

### Contactフォーム上の注意事項
以下を管理画面から差し替え出来るように実装
- [x] テキスト

### SP:
https://www.figma.com/file/4g6rmBH1DPWT9NBVV7OCfg/%E3%83%AF%E3%82%A4%E3%83%A4%E3%83%BC%E3%83%95%E3%83%AC%E3%83%BC%E3%83%A0?node-id=1755%3A26

### Desktop:
https://www.figma.com/file/4g6rmBH1DPWT9NBVV7OCfg/%E3%83%AF%E3%82%A4%E3%83%A4%E3%83%BC%E3%83%95%E3%83%AC%E3%83%BC%E3%83%A0?node-id=1828%3A257

**Comment by ruiishiguro** [comment]
動画は以下を仮で作成
https://www.youtube.com/watch?v=1nZey4JhP9o

**Comment by ruiishiguro** [comment]
7/5 デザインご提案
7/11 β版：サーバー上で動いている状態をご確認いただきます) / 7/5デザインに対するフィードバック
7/14 RC(Release Candidate)版 ：7/11のフィードバックを反映した状態
7/15 GA(General Availability)版 ：公開

**Comment by Sayuri-Y** [comment]
@ruiishiguro 

ちなみに動画なんですが、autoplay で流している箇所って youtube じゃなくて mp4 で素材もらえたりしますか？？

**Comment by ruiishiguro** [comment]
@Sayuri-Y 
かなり大きいデータですが以下ご確認ください。
https://www.dropbox.com/s/1m1ngkhsnxv1rsz/Placy_maika_sample_footage%20%282%29.mp4?dl=0

**Comment by Sayuri-Y** [comment]
@ruiishiguro 
めっちゃでかい〜！笑
本番動画データもでかいんですかね。。。

**Comment by ruiishiguro** [comment]
@Sayuri-Y 
サイズ指定してもらえれば圧縮したデータをご用意してもらえると思います。

**Comment by Sayuri-Y** [comment]
@ruiishiguro 

とりあえずメインの動画部分だけ、レイアウト調整中ですがざっくり動き大丈夫そうかご確認お願いいたします〜！
ミュートで流している部分は Youtube ではなく mp4 で埋め込みしているので、
本番データも mp4 でもらえれば実装できそうです。

今いれてる動画の元サイズがめちゃめや大きかったので、圧縮しても35MBあります。。。
軽ければ軽いほど嬉しいですが、
3~5MB とかが理想ですが、せめて10MB以下にはしたい！

**Comment by ruiishiguro** [comment]
@Sayuri-Y 
動画、良い感じかと。
了解しました。
3MBに収めてもらえるように先方に依頼をかけます。

**Comment by Sayuri-Y** [comment]
@ruiishiguro 

動画の件ありがとうございますー！
ちなみに、figma の知識があんまりなくて申し訳ないのですが。。。
このマップの箇所、背景透過書き出しってどうしたらできますかね？？
( 書き出すときに白背景が入ってしまう)

![main-map](https://user-images.githubusercontent.com/81949280/177892885-190a8cf1-1dfc-474b-845b-6cfabdad35e0.png)

**Comment by ruiishiguro** [comment]
@Sayuri-Y 
こちら、別途マップのデータを取り寄せるので一旦現状のままで進行していただけますか？

**Comment by ruiishiguro** [comment]
@Sayuri-Y 
mapですが、こちらを使ってもらえますか？
![placy-map](https://user-images.githubusercontent.com/1421966/177974498-909bf0b4-56ec-4280-878a-559ac86ba208.png)

**Comment by Sayuri-Y** [comment]
@ruiishiguro 

map の画像ありがとうございますー！
ひととおり実装完了したのでご確認をお願いいたします！

https://smack.gmprojects.dev/
https://smack.gmprojects.dev/wp-admin/

- 動画30MB入れるとちょいちょいWP止まるので見るに耐えないけど動画軽くしました。。。
- ogp:img 未作成です。

よろしくお願いいたします〜

**Comment by ruiishiguro** [comment]
@Sayuri-Y 
管理画面踏まえて確認しましたー。
バッチリかと思います！
ファビコンの設定までありがとうございます。
動画は現在オーダーしているので届いたら差し替えお願いします。
issue引き取りますね。

**Comment by ruiishiguro** [comment]
@Sayuri-Y 

今更ながら認証かけました。
https://smack.gmprojects.dev/

BASIC認証
smack
marunouchi

**Comment by Sayuri-Y** [comment]
@ruiishiguro 

ちなみに言い忘れてたのですが、
character の箇所のみ、キャラクターの画像をそのまま入れてもらえればその画像に背景グレー・ボーダー・角丸がつくように設定してあります！

**Comment by ruiishiguro** [comment]
一旦実装は完了しているのでクローズ。変更があればissueを分けて対応します。
