### ISSUE TITLE
デザインチェック

### ISSUE THREAD

**Issue by ruiishiguro** [ruiishiguro/smack#6]
https://smack.gmprojects.dev/

BASIC認証
smack
marunouchi

**Comment by ruiishiguro** [comment]
@mitsumashoko 
動画はデータをかなり圧縮しているので仮素材ですが、その他フレッシュな目線でデザインのチェックをお願いします。

**Comment by mitsumashoko** [comment]
@ruiishiguro 
ありがとうございます！　PC/SPともに確認しました！
一点　下部注意書き部分の住所部分も12pxにしてもらってもいいでしょうか？
（すみません　大きかったです）

**Comment by ruiishiguro** [comment]
@mitsumashoko 
週末にありがとうございます。
issue引き取ります。

**Comment by ruiishiguro** [comment]
展開済
クローズします。
