### ISSUE TITLE
注意書き部分の住所部分、文字サイズを変更

### ISSUE THREAD

**Issue by ruiishiguro** [ruiishiguro/smack#8]
デザインチェックより引き継ぎ
https://github.com/ruiishiguro/smack/issues/6

> 下部注意書き部分の住所部分も12pxにしてもらってもいいでしょうか？

**Comment by ruiishiguro** [comment]
@Sayuri-Y 

以下、赤枠部分のフォントサイズを12pxに変更をお願いします。

![スクリーンショット 2022-07-10 14 38 57](https://user-images.githubusercontent.com/1421966/178132840-41db5dd5-0028-48a8-b2c2-411e6af40110.png)

**Comment by Sayuri-Y** [comment]
@ruiishiguro 

こちら変更しました！
よろしくお願いいたします〜！

https://smack.gmprojects.dev/
smack / marunouchi

**Comment by ruiishiguro** [comment]
@Sayuri-Y 
確認しました！
バッチリかと思います！
クローズします。
