### ISSUE TITLE
App Downloadボタンをfixedにする

### ISSUE THREAD

**Issue by ruiishiguro** [ruiishiguro/smack#9]
App Downloadボタンを現状の場所でfixedにする

モバイルではURL欄に隠れないようにしたい。
![IMG_0161](https://user-images.githubusercontent.com/1421966/178180061-9a44789e-9d23-4656-8aac-52dc4367fab6.PNG)

**Comment by ruiishiguro** [comment]
参照
https://coliss.com/articles/build-websites/operation/css/css-cover-the-entire-height-of-the-screen.html

上記以外の方法でも構いません。

**Comment by ruiishiguro** [comment]
@Sayuri-Y 
こちら、見落としていました。
ボタンの位置調整をお願いします！

**Comment by Sayuri-Y** [comment]
@ruiishiguro 

ありがとうございます！
見落としてました。。。
送っていただいたリンクを参考に修正しました！

そしてスマホ時のボタンの位置がデザインと違うことに気づいたのでこちらも修正済みです！

![スクリーンショット 0004-07-11 12 44 57](https://user-images.githubusercontent.com/81949280/178184823-63ab2589-3efd-446d-bd32-30114c4e143f.png)

**Comment by ruiishiguro** [comment]
@Sayuri-Y 
バッチリです！
こちらで確認に出しますー。ありがとうございます。
